apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://localhost:8082/root/inception-of-things.git
    targetRevision: HEAD
    path: p3/confs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
