global:
  hosts:
    domain: localhost
    externalIP: 127.0.0.1

gitlab:
  webservice:
    service:
      type: NodePort
      nodePort: 32080
    ingress:
      enabled: false

nginx-ingress:
  enabled: false

certmanager:
  install: false

prometheus:
  install: false

gitlab-runner:
  install: false
