apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
  namespace: apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>App 1</title></head>
      <body><h1>Hello from App 1</h1></body>
    </html>
