apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
  namespace: apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>App 2</title></head>
      <body><h1>Hello from App 2</h1></body>
    </html>
