apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-html
  namespace: apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>App 3</title></head>
      <body><h1>Hello from App 3</h1></body>
    </html>
